//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosk_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_PAYMENTS
    {
        public int PAYMENT_ID { get; set; }
        public int CUST_REG_ID { get; set; }
        public string BILLER { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime DATE_TIME { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
