//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosk_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Priyanka_DBEntities : DbContext
    {
        public Priyanka_DBEntities()
            : base("name=Priyanka_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL_PAYMENTS> BILL_PAYMENTS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
    }
}
